API Camera Feed Implementation
Team-Cartographer/SUITS-2024-LMCC pull request #40
Opened 2024-02-10 07:03 UTC by ivanvuong

-- Implemented Camera Feed to the Screen Two Console 
-- Created helpers that call HoloLens API for the video and returned styled video in the component 

For now, undefined is returned, which is why there is a blank screen. Commented out original camera feed function in 2 different places, **exporting in @camera_feed.txt, and **import&calling in @/screen_two/page.tsx, instead implementing youtube video rendering 

-- Made a basic "TempYoutubeVideo" function that renders a youtube video. 

-- Commented out original code in page.tsx regarding Telemetry Page 

UNSURE of general name of function in page.tsx (remains "TelemetryPage()")
UNSURE of formatting of the video: size, etc

Current implementation of Screen Two (Youtube Video)
![Screenshot 2024-02-09 224620](https://github.com/Team-Cartographer/SUITS-2024-LMCC/assets/149543946/4ff9f6a8-f72b-4af9-a4cd-d6634d20521d)

Commented out implementation of the API Camera Feed 
![Screenshot 2024-02-09 224656](https://github.com/Team-Cartographer/SUITS-2024-LMCC/assets/149543946/5bb60043-d7cf-443d-a2fb-9af34a221a07)

2024-02-10 07:35 UTC, abhi-arya1 requested changes
take a look at comments--we'll go over final stuff in the code review, but looks good and works rn 😄

2024-02-10 07:35 UTC, abhi-arya1 commented on client/components/hmd_link/camera_feed.tsx
> +            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
use TailwindCSS styling for this (look @ map component to see how that works) since that is our project convention

2024-02-10 07:35 UTC, abhi-arya1 commented on client/components/hmd_link/camera_feed.tsx
> +    try { // FIXME: PR will be approved w/ this, but this path will need to be changed once we get HoloLenses
leaving this comment here so you can read it--don't worry ab it tho

2024-02-10 07:35 UTC, abhi-arya1 commented on client/components/hmd_link/camera_feed.tsx
> +export function TempYoutubeVideo() {
make sure to not have `export` and `export default` in the same file. I've fixed this this time around, but letting you know for nxt time

2024-02-10 07:35 UTC, abhi-arya1 commented on client/app/screen_two/page.tsx
> +          <Map />
there's an emergent issue with the map (yet again). i'll be opening an issue. We'll merge this PR with that `<Map />` line commented out as such: `{ /* <Map /> */ }`.

2024-02-10 07:36 UTC, abhi-arya1 commented on client/components/ui/map.tsx
> +        return <p>Error: &quot;{err}&quot; was thrown while loading Map</p>
you ran into a merge conflict here--again, i've fixed it for now, but make sure to `git merge main` *before* your PR next time

2024-02-12 18:36 UTC, abhi-arya1 reviewed
everything looks good and works well, but there's an issue with the map flexbox (that's not on your end but on the integration of all the components--once that's fixed then we can merge

2024-02-12 18:56 UTC, abhi-arya1 approved these changes
map fixed, LGTM (do not merge, a co-lead will do this)

2024-02-12 19:28 UTC, Turfader approved these changes
I trust that this doesn't break anything. Good luck

2024-02-12 19:47 UTC, merged