Python type hints
Team-Cartographer/SUITS-2024-LMCC pull request #57
Opened 2024-03-04 07:38 UTC by DatsIsaiah

Added type hints instead of notation (previously caused due to misunderstanding)

2024-03-04 07:44 UTC, abhi-arya1 requested changes
stuff looks good -- look at my comments and remove unused imports

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/functions/astar.py
> +from typing import List, Tuple, Optional
don't repeat imports please

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/functions/astar.py
> +        self.position: Tuple[int, int] = position
don't type hint variables because it causes asymmetry (sorry i thought i mentioned this earlier, if i didn't, let me know and i'll fix it)

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/functions/astar.py
> +            path: List[Tuple[int, int]] = []
same as the above comment applies here

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/utils.py
> +        # Check if the distance between the check point and the current pin is within the specified radius
thank you for all of these comments, that looks good 👍

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/posters.py
> +    - args (Dict[str, Any]): A dictionary containing the following keys:
don't type hint comments, only function headers itself. Typehinting comments doesn't do anything for VSCode's intellisense to suggest autocomplete stuff

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/getters.py
> +        path_json: str = json.dumps({'path': path})
again, variable type hints not needed

(also, `json.dumps` returns a Dictionary, not a string)

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/getters.py
> +        radius: int = 3
unnecessary, we already know that radius is an int by definition

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/getters.py
> +        data: Union[Dict[str, Any], None] = json.load(json_file)
not needed here either

2024-03-04 07:44 UTC, abhi-arya1 commented on server/api/getters.py
> +from io import BytesIO
we don't need this import if you remove the type hint (because that one is unneccesary as well)

2024-03-04 07:48 UTC, Turfader requested changes
see discord

2024-03-05 04:17 UTC, Turfader approved these changes
Much better

2024-03-05 07:13 UTC, abhi-arya1 approved these changes
LGTM

2024-03-05 07:13 UTC, abhi-arya1 commented
merging with bypass because i just added a stdlib import

2024-03-05 07:13 UTC, merged